// Copies the design system into a checkout of the Lovable design-system project's repository
// (Lovable's TanStack "custom design system" template), then you review, commit and push there.
//
//   node scripts/sync-lovable.mjs ../tailor-brands-home-assignment
//
// This repo stays the source of truth. The sync replaces only the paths the design system owns
// (OWNED below) and leaves Lovable's template (routes, router, vite config, preview plugin,
// package.json, .lovable/meta.yaml and the generated .lovable/design-system.json + rules) alone.
// Anything edited inside an owned path in the Lovable repo is overwritten by the next sync.
import { cpSync, existsSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const target = process.argv[2];
if (!target) {
  console.error('usage: node scripts/sync-lovable.mjs <path-to-lovable-repo-checkout>');
  process.exit(1);
}
const dest = resolve(target);
const src = resolve(new URL('..', import.meta.url).pathname);
if (!existsSync(join(dest, '.lovable/meta.yaml')) || !existsSync(join(dest, 'mockupPreviewPlugin.ts'))) {
  console.error(`${dest} doesn't look like a Lovable design-system checkout (no .lovable/meta.yaml or mockupPreviewPlugin.ts)`);
  process.exit(1);
}

// Paths the design system owns in the Lovable repo. Directories are replaced wholesale, so files
// deleted here are deleted there too.
const OWNED = [
  'src/index.ts',
  'src/components',
  'src/styles',
  'src/pages/Showcase.tsx',
  'tokens/tokens.json',
  'tokens/tokens.base.json',
  'scripts/build-tokens-css.mjs',
  '.lovable/system.md',
  '.dsignore',
];
// Storybook-only files: the Lovable project has no Storybook, so they would break its typecheck.
const skip = (path) => /\.stories\.tsx?$/.test(path);

const copied = [];
for (const path of OWNED) {
  const from = join(src, path);
  const to = join(dest, path);
  rmSync(to, { recursive: true, force: true });
  cpSync(from, to, {
    recursive: true,
    filter: (file) => !skip(file),
  });
  copied.push(path);
}

// App stylesheet of the Lovable project: loaded by the showcase route and injected into every
// component/mockup preview frame by mockupPreviewPlugin (APP_CSS_IMPORT = "@/styles.css").
writeFileSync(join(dest, 'src/styles.css'), `/* GENERATED by scripts/sync-lovable.mjs in Moragron/tailor-brands-design-system — do not edit here.
 * Stylesheet of the design-system project itself (showcase + Lovable's component previews), wired
 * exactly like a connected Tailwind 4 project. Excluded from connected projects by .dsignore.
 */
@import "tailwindcss";
@import "./styles/index.css";
@import "./styles/depth.css"; /* off unless <html data-tb-depth> is not "flat"; the showcase toggles it */
@import "./styles/base.css";
`);
copied.push('src/styles.css (generated)');

const count = (dir) => readdirSync(dir, { recursive: true }).filter((f) => statSync(join(dir, f)).isFile()).length;
console.log(`synced into ${relative(process.cwd(), dest) || dest}:\n  ${copied.join('\n  ')}`);
console.log(`(${count(join(dest, 'src/components'))} component files, ${count(join(dest, 'src/styles'))} style files)`);
console.log('Review with `git -C <repo> status` / `git diff`, then commit and push. Lovable syncs the push; select Release version to ship it.');
